.\"
.TH PHOTOFLARE "1" "April 2020" "1.6.4"
.SH NAME
photoflare \- Simple but powerful Cross Platform Image Editor
.SH DESCRIPTION
This is an effort to bring quick, simple but powerful image editing to the
masses. Photoflare is inspired by the image editor currently only available
on Microsoft Windows – PhotoFiltre. However, it will not be a straight clone.
It is being built from the ground up to be much improved and cross platform too!
.SH SEE ALSO
.BR http://photoflare.io/
.br
.BR https://github.com/PhotoFlare/photoflare
.SH COPYRIGHT
Copyright \(co 2015\-2020 Dylan Coakley.
.br
Distributed under the GNU GPL-3+ open source license.
