name: photoflare
version: 1.7.0
summary: PhotoFlare
description: Simple but powerful Cross Platform image editor
icon: installers/deb/DEBIAN/usr/share/icons/hicolor/48x48/apps/photoflare.png
type: app

base: core24
confinement: classic
grade: stable

apps:
  photoflare:
    command: $SNAP/usr/local/bin/photoflare
    desktop: usr/local/share/applications/photoflare.desktop

parts:
  photoflare:
    source: .
    source-type: local
    plugin: nil
    build-packages:
      - qt6-base-dev
      - qt6-tools-dev-tools
      - libgraphicsmagick++-dev
      - libomp-dev
    override-build: |
      qmake6 $CRAFT_PART_SRC
      make -j$(nproc)
      make install INSTALL_ROOT=$CRAFT_PART_INSTALL
    stage-packages:
      - libgraphicsmagick++-q16-12t64
      - libomp5-18
      - libqt6printsupport6
      - qt6-image-formats-plugins
