name: photoflare
version: 1.6.12
summary: PhotoFlare
description: Simple but powerful Cross Platform image editor
icon: installers/deb/DEBIAN/usr/share/icons/hicolor/48x48/apps/photoflare.png
type: app

base: core18
confinement: classic
grade: stable

apps:
  photoflare:
    command: desktop-launch $SNAP/usr/local/bin/photoflare
    desktop: usr/local/share/applications/photoflare.desktop

parts:
  photoflare:
    after: [desktop-qt5]
    source: https://github.com/PhotoFlare/photoflare.git
    source-type: git
    source-tag: 'v1.6.12'
    plugin: qmake
    qt-version: qt5
    build-packages:
      - qtbase5-dev
      - qttools5-dev-tools
      - libgraphicsmagick++-dev
      - libomp-dev
    stage-packages:
      - libgraphicsmagick++-q16-12
      - libomp5
      - libqt5printsupport5
      - qt5-image-formats-plugins
