name: Build Snap

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  snap:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: photoflare-snap
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error

      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.snapcraft.outputs.snap }}
